### ISSUE TITLE
Array of vectors

### ISSUE THREAD

**Issue by archasek** [Semafind/semadb#15]
Hey there! 

Do you support arrays of vectors? I am wondering how to perform a similarity search when I have a list of keywords/tags. They vary a lot so I probably want to avoid text or stringArray search and use similarity search instead. 

Is aggregation the only option here, or there's a way to actually search semantically for a specific keyword within a larger list?
Thanks

**Comment by nuric** [comment]
Hmm, there isn't arrays of vectors type since each vector would have to be indexed individually. You can have multiple vectors per point but they are separate indices, mostly used for multi-modal stuff, for example image embedding and text embedding side-by-side. The stringArray type is text based search often used for things like filtering categories etc.

One option would be to embed each keyword / tag individually and then set the point's vector to the average of those. This would be like a vector based bag-of-words model. So a search containing similar words embedded in the same way would retreive the closest points.

Alternatively, I've seen people concatenate the words into a single string like "car black SUV" and then embed that directly.

**Comment by archasek** [comment]
Okay, thank you very much!
